### PR TITLE
remove key in separate ssm command

### PR DESCRIPTION
**Pull request by adam-kiss-sg**
Thanks a lot for this script. 

Had to modify it a bit, because for some reason it was waiting the whole 15 sec at the `aws ssm wait command-executed` part, then returned with an auth error (because the key was already deleted from the server at that point).

### CODE REVIEW

**Comment by elpy1** [comment]
Cool. Thanks for PR - will take a look, probably on the weekend.

It's strange because I never experienced this issue when testing. Would you mind providing:
- local OS
- aws cli version you're using
- server distro and version
- high latency to server?

Thanks.

**Comment by adam-kiss-sg** [comment]
Hi!

OS: win10 + wsl2
AWS CLI: aws-cli/2.3.3 Python/3.8.8 Linux/5.10.16.3-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off
server distro: Ubuntu 20.04.2 LTS

> high latency to server?

no, server is in EU and so am I

**Comment by elpy1** [comment]
I was able to replicate the issue on a server running ubuntu 20. Would you mind trying after latest commit and let me know if it fixes the issue?

**Comment by adam-kiss-sg** [comment]
It works! Thank you!

**Pull request closed without merging**
